name: projet
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  provider: ^6.0.3
  table_calendar: ^3.0.6
  image_picker: ^0.8.5+3
  connectivity_plus: ^2.3.6
  font_awesome_flutter: ^10.1.0
  dropdown_search: ^5.0.2
  photo_view: ^0.14.0
  smart_select: ^4.3.2
  cron: ^0.5.0
  pdf: ^3.8.3
  whatsapp_share: ^1.1.1

  
  


  
  cupertino_icons: ^1.0.2
  a: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

